.pre-commit-hooks.yaml, README.md
This enables using the repository with [pre-commit][1].
I tested this with
pre-commit try-repo https://github.com/colindean/secrets.git secrets --verbose --all-files
And the output:
```
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/colindean/secrets.git
rev: 3fe8bf59a62e00fbbdf7de47f57c32058bd5f2ee
hooks:
-   id: secrets
===============================================================================
[INFO] Initializing environment for https://github.com/colindean/secrets.git.
[INFO] Installing environment for https://github.com/colindean/secrets.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a …
```
=> Adds pre-commit configuration

README.md
`cargo` has a neat trick where users can install a Rust program from the git URL.
=> adds an alternative installation method to README

README.md
Remove `$` from example code of what user might add to a `pre-commit` script, since it's not a command they would run from the command line. 
Likewise, adds a `$` to the `cargo install` command, since that's one that the user would run on the command line.
=> Fixes command example notation in README

src/main.rs
One issue with PR #15 is if user runs `ripsecrets --install-pre-commit --strict-ignore` (see https://github.com/sirwart/ripsecrets/pull/15#issuecomment-1106872423)
Since the `--install-pre-commit` flag _always_ ignores `.secretsignore`file(s), running `ripsecrets --install-pre-commit` is effectively the same as running `ripsecrets --install-pre-commit --strict-ignore`. And in fact, the same code is called from `main.rs`.
In an effort to avoid some possible confusion for users, this PR makes the tool print an informal error message and exit if a user runs `ripsecrets --install-pre-commit --strict-ignore`:
```text
Error: Cannot use both --strict-ignore and --install-pre-commit.
--strict-ignore is always used when automatically installing the pre-commit hook. Use `--install-pre-commit` …
```
=> adds an informal warning against using both flags

src/pre_commit.rs
If no `pre_commit_dir` exists the `--install-pre-commit` option creates a pre-commit hook with the file name `pre_commit` in `.git/hooks/` resulting in the pre-commit hook not working. This pr fixes the typo.
=> Fix typo in pre-commit file name

src/main.rs
Has `main` return Rust's `Result` rather than "raw" exit codes, which I think will provide more cross-platform compatibility. It's also more in-line with common Rust patterns, as I understand them. 
Also removes `impl std::error::Error for UsageError {}`, which I didn't see being used anywhere but I could be wrong. 
I'll note here that [the very new Rust 1.61 introduces a more sophisticated error code wrapper](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html#custom-exit-codes-from-main).
=> re-works src/main.rs to better handle errors.

.github/workflows/benchmark.yml, benches/find_secrets.rs, src/lib.rs, src/main.rs
On each commit to `main`, run benchmarks and publish them to the `gh-pages` branch. That branch can be configured as the source of GitHub Pages, so it gets built and published on each change. See https://lafrenierejm.github.io/ripsecrets/dev/bench/ for an example of benchmarks published from my fork.
=> Publish benchmarks to GitHub Pages

.github/workflows/benchmark.yml, .github/workflows/ci.yml, .github/workflows/release.yml, flake.nix
This adds a GitHub Actions workflow for building and uploading a Docker image to Docker hub. The workflow is triggered when a new tag is added or it can be run manually. The prerequisites are
- a Docker Hub account with the same username as GitHub;
- a Docker Hub repository with the same name as the repository (in this case "ripsecrets", though forks can rename); and
- the Docker Hub username and a write token saved in GitHub Secrets as `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`, respectively.
See <https://hub.docker.com/r/lafrenierejm/ripsecrets/tags> for an example of an image built from the [corresponding workflow](https://github.com/lafrenierejm/ripsecrets/actions/runs/3579351735) on my fork.
The main limitation of this current approach is that the image that's built and uploaded is …
=> Build Docker image and publish to Hub on tag

.github/workflows/benchmark.yml, .gitmodules
Workaround for https://github.com/sirwart/ripsecrets/issues/48. See https://github.com/lafrenierejm/ripsecrets/actions/runs/3607165523/jobs/6079002306 for a successful benchmark run on my fork.
=> Remove getsentry/sentry submodule

.pre-commit-hooks.yaml, README.md
This should enable a pre-commit config to use a ripsecrets binary already installed instead of having to build ripsecrets from source. Notably, this should allow Homebrew users to include precommit and ripsecrets in a Brewfile and avoid having to also have a rust build environment installed just for ripsecrets usage with recommit.
Closes #50
=> Provide hook option to use a locally-installed ripsecrets

README.md
Hi @sirwart , thanks for the great tool. I'm just writing up a book section on how to set up ripsecrets, via pre-commit, and I thought I'd try improve the instructions in the repo whilst I'm at it.
I made these improvements:
1. Improve some terminology - pre-commit uses "hooks" not "plugins"
2. Remove advice about updating regularly - I think this applies to all pre-commit users, who should be aware of the `pre-commit autoupdate` command, or use pre-commit.ci that runs this for you.
3. Show the sample config first, then explain the options.
4. Edit to recommend the `ripsecrets` hook, because since version 2.21.0, pre-commit can bootstrap Rust if it is unavailable ([pre-commit PR](https://github.com/pre-commit/pre-commit/pull/2534), [open docs improvement …
=> Improve pre-commit framework docs

Cargo.lock, Cargo.toml, src/main.rs
Clap recently got into v4.X.X, so I figured it'd be nice to get ripsecrets using the current up-to-date version, v4.2.5. Required only a minor tweak to reach functional parity with 3.X.X. Should work exactly the same after this PR.
=> Upgrades clap dependency

.github/workflows/release.yml
See [here](https://github.com/lafrenierejm/ripsecrets/actions/runs/6387521064) for an example of a successful workflow run.
=> Correct the name of OCI Nix package in release GHA workflow

Cargo.lock, Cargo.toml, build.rs, src/args.rs, src/main.rs
Fixes #73 by generated a manpage via `clap_mangen`.
<details>
<summary>This is the output nroff I get when building locally.</summary>
```nroff
.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH ripsecrets 1  "ripsecrets 0.1.7" 
.SH NAME
ripsecrets \- A command\-line tool to prevent committing secret keys into your source code
.SH SYNOPSIS
\fBripsecrets\fR [\fB\-\-install\-pre\-commit\fR] [\fB\-\-strict\-ignore\fR] [\fB\-\-only\-matching\fR] [\fB\-\-additional\-pattern\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fISource files\fR] 
.SH DESCRIPTION
ripsecrets searches files and directories recursively for secret API keys.
It\*(Aqs primarily designed to be used as a pre\-commit to prevent committing
secrets into version control.
.SH OPTIONS
.TP
\fB\-\-install\-pre\-commit\fR
Install …
```
=> Generate manpage as part of build

.github/workflows/release.yml, Cargo.lock, flake.lock, flake.nix
Addresses #77.
This new step requires the presence of a GitHub Actions Secret named `CRATES_IO_API_TOKEN` with access to publish the `ripsecrets` crate.
Dependencies were updated to avoid versions that have been yanked.
=> Add `publish-crate` step to release workflow

flake.lock, flake.nix
This was prompted by crane deprecating the `mkLib` function. I'd like to stay on top of the Nix dependencies just to minimize any maintenance burden.
=> Update Nix inputs

src/lib.rs
Currently, the secretsignore specified files are added with the lowest precedence, so if some other regular gitignore file happens to unignore some pattern (i.e. with `!pattern`), its not easy to have the ripsecrets ignore these files.
This PR changes the behavior so that the file patterns from the secretsignore have the highest precedence. Im happy to modify this to flag this behavior, because this does potentially cause some difference in behavior, but I think that the previous behavior seemed unintended.
=> secretsignore file pattern has the highest precedence

.github/workflows/release.yml
upload-artifact v3 was deprecated.
https://github.com/actions/upload-artifact
> Warning
> actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions.
CI failed and outputted the log `Error: Missing download info for actions/upload-artifact@v3`.
- https://github.com/sirwart/ripsecrets/issues/95
I'm not sure if this is related to the deprecation, but we should update the action.
=> chore: update upload-artifact to v4

.github/workflows/release.yml
Checkout the repository before running install-nix-action.
CI failed.
- https://github.com/sirwart/ripsecrets/issues/95
https://github.com/sirwart/ripsecrets/actions/runs/14021086096/job/39253150448
```
Run nix develop --command cargo publish
path '/home/runner/work/ripsecrets/ripsecrets' does not contain a 'flake.nix', searching up
error: could not find a flake.nix file
Error: Process completed with exit code 1.
```
flake.nix exists in the repository, but the repository wasn't checked out.
https://github.com/sirwart/ripsecrets/blob/main/flake.nix
=> ci: checkout the repository before running install-nix-action

CHANGELOG.md, Cargo.lock, Cargo.toml
Fixes https://github.com/sirwart/ripsecrets/actions/runs/15265566715/job/42930528887#step:4:753,
> ++ command cargo check --release --locked --all-targets
> error: the lock file /build/source/Cargo.lock needs to be updated but --locked was passed to prevent this
> If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
=> fix: sync Cargo.toml and Cargo.lock
